import type { Metadata } from 'next';
import { Manrope } from 'next/font/google'; // Replace Inter with Manrope
import './globals.css';
import { getCategories } from './(server)/services/category';
import { getProducts } from './(server)/services/product';
import ReduxProvider from '@/lib/provider';

const manrope = Manrope({ subsets: ['latin'] }); // Use Manrope instead

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function DefaultLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();
  const products = await getProducts();

  return (
    <html lang="en" className={manrope.className}>
      <ReduxProvider categories={categories} products={products}>
        <body>{children}</body>
      </ReduxProvider>
    </html>
  );
}
