import type { Metadata } from 'next';
import { Manrope } from 'next/font/google'; // Replace Inter with Manrope
import './globals.css';

const manrope = Manrope({ subsets: ['latin'] }); // Use Manrope instead

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DefaultLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manrope.className}>
      <body>{children}</body>
    </html>
  );
}
