import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../globals.css';
import NavBar from '@/app/(shared)/NavBar/NavBar';
import Footer from '@/app/(shared)/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="blackBackground"></div>
        <main className="main">
          <NavBar />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
